---

- name: Install Node.js and npm with specific version using nvm
  hosts: servers
  become: true

  tasks:
    - name: Install curl (required for nvm installation)
      ansible.builtin.shell:
        cmd: "apt-get install -y curl"
        creates: "/usr/bin/curl"  # Check if curl is already installed

    - name: Install nvm
      ansible.builtin.shell:
        cmd: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash && export NVM_DIR={{ ansible_env.HOME }}/.nvm && [ -s $NVM_DIR/nvm.sh ] && source $NVM_DIR/nvm.sh"
        executable: /bin/bash

    - name: Install Node.js and npm using nvm
      ansible.builtin.shell:
        cmd: |
          source $NVM_DIR/nvm.sh
          nvm install "{{ nodejs_version }}"
          nvm use "{{ nodejs_version }}"
          npm install -g npm@"{{ npm_version }}"
        executable: /bin/bash
      environment:
        NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
